### PR TITLE
Fix up package runtime dependencies

### PR DESCRIPTION
**Pull request by Anthchirp**
* regenerate the recipe using grayskull
* add setuptools runtime dependency (cf. https://github.com/astropy/pytest-doctestplus/issues/93#issuecomment-723443925 and https://github.com/astropy/pytest-doctestplus/pull/132) 
* remove numpy runtime dependency ([dropped in 0.5.0](https://github.com/astropy/pytest-doctestplus/blob/master/CHANGES.rst#050-2019-11-15))
* add myself as maintainer

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
@conda-forge/pytest-doctestplus this is ready for review/merging

**Comment by mwcraig** [comment]
@Anthchirp -- thank you for the pull request and for volunteering to be a maintainer! I'm going to switch a couple of the URLs back to github (for this package it is really the home, the docs, and dev location) then will merge it.

**Comment by Anthchirp** [comment]
Having the different URLs makes it easier to find the related places. If they're all the same only one will be shown anyway.

**Comment by mwcraig** [comment]
Yes, but astropy.org, for example, doesn't have any information about the package...

**Comment by Anthchirp** [comment]
Okay. But pypi does, and having that link handy makes it easier to check the package history, download the source, verifying the hash etc :slightly_smiling_face:

**Comment by Anthchirp** [comment]
(when you're happy with the URL changes you'll need to trigger a rerendering before merging)

**Comment by mwcraig** [comment]
Good point, pypi makes much more sense as doc url. @conda-forge-admin, please rerender

**Comment by mwcraig** [comment]
Welcome aboard, @Anthchirp, merging!

**Pull request merged**
